client/FileStorage.Web/ViewModels/ErrorViewModel.cs
namespace FileStorage.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

client/FileStorage.Web/ViewModels/FileInfoViewModel.cs
namespace FileStorage.Web.ViewModels
{
    public class FileInfoViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public int Size { get; set; }
    }
}

client/FileStorage.Web/ViewModels/OrganizationViewModel.cs
namespace FileStorage.Web.ViewModels
{
    public class OrganizationViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

client/FileStorage.Web/Controllers/OrganizationsController.cs
using FileStorage.Core.Services;
using FileStorage.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FileStorage.Web.Controllers
{
    [Route("organizations")]
    [Route("")]
    public class OrganizationsController : Controller
    {
        private readonly IOrganizationService m_OrganizationService;
        public OrganizationsController(IOrganizationService orgService)
        {
            m_OrganizationService = orgService;
        }

        [HttpGet]
        public async Task<IActionResult> Organizations()
        {
            var orgs = await m_OrganizationService.GetAsync();
            List<OrganizationViewModel> orgsViewModel = orgs.Select(o => new OrganizationViewModel { Id = o.Id, Name = o.Name }).ToList();

            ViewBag.Organizations = new SelectList(orgsViewModel, nameof(OrganizationViewModel.Id), nameof(OrganizationViewModel.Name), null);

            ViewData["Title"] = "Available organizations";

            return View();
        }
    }
}

client/FileStorage.Web/Controllers/StorageController.cs
using FileStorage.Core.Models;
using FileStorage.Core.Services;
using Microsoft.AspNetCore.Mvc;

namespace FileStorage.Web.Controllers
{
    [Route("Files")]
    public class StorageController : Controller
    {
        private readonly IFileStorageService m_FileStorageService;
        public StorageController(IFileStorageService fileStorageService)
        {
            m_FileStorageService = fileStorageService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int orgId)
        {
            var model = await m_FileStorageService.GetFilesInfo(orgId);
            return PartialView(model);
        }

        [HttpPost("UploadFile")]
        public async Task<IActionResult> UploadFile([FromForm] IFormFile file, int orgId)
        {
            var result = await m_FileStorageService.UploadFile(file, orgId);
            return PartialView("Index", new List<StoredFileInfo>{ result });
        }

        [HttpDelete("DeleteFile/{fileId}")]
        public async Task<IActionResult> DeleteFile(string fileId, int orgId)
        {
            await m_FileStorageService.DeleteFile(fileId, orgId);
            return Ok();
        }
    }
}

client/FileStorage.Web/Views/Organizations/Organizations.cshtml
@model List<OrganizationViewModel>

<div id="modal" class="modal fade" tabindex="-1" aria-hidden="true">
</div>

<div id="deleteFileModal" class="d-none">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                Are you sure you want to delete the file?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button id="deleteFileConfirmBtn" type="button" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</div>

<div>
    <label>Organizations</label>
    <select id="orgSelector" asp-items="@ViewBag.Organizations" class="form-select form-select-lg mb-3" aria-label="Large select example">
        <option selected value=null></option>
    </select>
    <div id="loader" class="spinner-border d-none" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>

    <div class="mb-3">
        <label for="uploadFileInput" class="form-label">Default file input example</label>
        <input class="form-control" type="file" id="uploadFileInput">
        <button id="uploadFileBtn" type="button" class="btn btn-primary">Upload a file</button>
    </div>
    <div class="files-table-container">
        <div class="files-table-buttons">
            <button id="deleteFileBtn" type="button" class="btn btn-danger">Delete</button>
        </div>
        <table id="filesTable" class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Size</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/js/organizations/organizations.js"></script>
}

@section Styles {
    <link rel="stylesheet" href="~/css/organizations.css" />
}

client/FileStorage.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileStorage.Web.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FileStorage.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Index">Storage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FileStorage.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

client/FileStorage.Web/Views/Storage/Index.cshtml
@model IEnumerable<StoredFileInfo>

@foreach (var fileInfo in Model)
{
    <tr data-id="@fileInfo.Id">
        <td>@fileInfo.Id</td>
        <td>@fileInfo.Name</td>
        <td>@fileInfo.Size</td>
    </tr>
}